# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<-SCRIPT
sudo dnf install qemu-system-x86 /vagrant/osbuild*.rpm -y
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "fedora/30-cloud-base"
  config.vm.box_version = "30.20190425.0"
  config.vm.provider "libvirt" do |v|
    v.memory = 4096
  end
  config.vm.provision "shell", inline: $script
end
