# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<-SCRIPT
packages=$(find /vagrant/testing-rpms -name '*.noarch.rpm')
sudo dnf remove -y $(basename -a ${packages[@]} | sed 's/-[0-9].*.rpm$//') || true
sudo dnf install qemu-system-x86 /vagrant/testing-rpms/*.noarch.rpm -y
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "fedora/30-cloud-base"
  config.vm.box_version = "30.20190425.0"
  config.vm.provider "libvirt" do |v|
    v.memory = 4096
  end
  config.vm.provision "shell", inline: $script
end
