
pull_request_rules:
  - name: Automatic review for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - title~=^Bump [^\s]+ from ([\d]+)\..+ to \1\.
      - "#changes-requested-reviews-by=0"
      - base=main
    actions:
      review:
        type: APPROVE
        message: Automatically approving dependabot (minor version bump)
      label:
        add:
          - ci:automerge

  - name: Dismiss reviews for non trusted authors
    conditions:
      - base=main
      - author!=@Schutzbot
    actions:
      dismiss_reviews:
        approved: True
        changes_requested: True
