# https://packit.dev/docs/configuration/

specfile_path: osbuild.spec

files_to_sync:
    - osbuild.spec
    - .packit.yaml

upstream_package_name: osbuild
downstream_package_name: osbuild

copy_upstream_release_description: true

upstream_tag_template: v{version}

srpm_build_deps: []
actions:
  get-current-version: bash -c "git describe --tags --abbrev=0 | sed 's|v||'"

# Handle only releases without a "dot" (e.g. v88.2), since "dot" releases should never be released to Fedora
# "dot" releases are used only for "backports" to RHEL.
upstream_tag_include: 'v\d+'

jobs:
- &copr
  job: copr_build
  trigger: pull_request
  targets:
  - centos-stream-8-aarch64
  - centos-stream-8-x86_64
  - centos-stream-9-aarch64
  - centos-stream-9-x86_64
  - epel-8-aarch64
  - epel-8-x86_64
  - epel-9-aarch64
  - epel-9-x86_64
  - fedora-all-aarch64
  - fedora-all-s390x
  - fedora-all-ppc64le
  - fedora-all
- <<: *copr
  trigger: commit
  branch: main
  owner: "@osbuild" # copr repo namespace
  project: osbuild  # copr repo name so you can consume the builds
- job: propose_downstream
  trigger: release
  dist_git_branches:
  - fedora-all
- job: koji_build
  trigger: commit
  dist_git_branches:
  - fedora-all
- job: bodhi_update
  trigger: commit
  dist_git_branches:
  - fedora-branched # rawhide updates are created automatically
