# we have the specfile in the root of our repository
specfile_path: osbuild.spec
# when doing an update in Fedora, we want to copy the spec file and the config file
synced_files:
  - osbuild.spec
  - .packit.yaml
upstream_project_name: osbuild
downstream_package_name: osbuild
jobs:
  # trigger a COPR build for push events in open PRs
  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
      - fedora-30-x86_64
      - fedora-31-x86_64
      - fedora-rawhide-x86_64
  # this is triggered by a commit on src.fedoraproject.org, not Github!
  # e.g. in case of mass rebuild or automated changes of spec file (e.g. Python packagers)
  # it will create a PR on Github with changes in synchronized files
  - job: sync_from_downstream
    trigger: commit
  # create a PR on src.fedoraproject.org containing updated spec file and new sources (tarball)
  # triggered by Github release
  - job: propose_downstream
    trigger: release
    metadata:
      dist-git-branch: master
  # The same as above only for f31
  - job: propose_downstream
    trigger: release
    metadata:
      dist-git-branch: f31
  - job: propose_downstream
    trigger: release
    metadata:
      dist-git-branch: f30
