FROM fedora:latest
RUN dnf install -y \
    findutils \
    fish \
    fpaste \
    git \
    hostname \
    jq \
    libguestfs-tools libguestfs \
    libosinfo \
    make \
    qemu-img \
    qemu-system-x86 \
    osbuild \
    osbuild-ostree \
    podman \
    pylint \
    python3-autopep8 \
    python3-devel \
    python3-docutils \
    python3-enchant \
    python3-iniparse \
    python3-mako \
    python3-jsonschema \
    python3-pip \
    python3-pycodestyle \
    python3-pylint \
    python3-pytest \
    rpm-build \
    rpmlint \
    selinux-policy-devel \
    skopeo \
    the_silver_searcher \
    tree
