FROM fedora:latest
RUN dnf install -y \
    bat \
    findutils \
    fish \
    fpaste \
    git \
    glibc-langpack-en \
    hostname \
    ipython3 \
    jq \
    libguestfs-tools libguestfs \
    libosinfo \
    lsof \
    make \
    packit \
    parted \
    qemu-img \
    qemu-system-x86 \
    osbuild \
    osbuild-ostree \
    podman \
    pylint \
    python3-autopep8 \
    python3-boto3 \
    python3-devel \
    python3-docutils \
    python3-enchant \
    python3-iniparse \
    python3-mako \
    python3-jsonschema \
    python3-pip \
    python3-pycodestyle \
    python3-pylint \
    python3-pytest \
    python3-pyyaml \
    rpm-build \
    rpmlint \
    selinux-policy-devel \
    skopeo \
    strace \
    the_silver_searcher \
    tree

WORKDIR /workspaces/osbuild
