FROM fedora
RUN dnf install -y \
    fish \
    git \
    jq \
    make \
    qemu-img \
    osbuild \
    osbuild-ostree \
    pylint \
    python3-autopep8 \
    python3-devel \
    python3-docutils \
    python3-iniparse \
    python3-jsonschema \
    python3-pip \
    python3-pylint \
    python3-pytest \
    rpm-build \
    selinux-policy-devel
