pipeline {
    agent none

    options {
        timestamps()
        ansiColor('xterm')
    }

    stages {
        stage("Functional Testing") {
            parallel {
                stage('Fedora 31 image') {
                    agent {
                        label "fedora31"
                    }
                    environment {
                        TEST_TYPE = "image"
                    }
                    steps {
                        sh "jenkins/run_tests.sh"
                    }
                }
                stage('Fedora 32 image') {
                    agent {
                        label "fedora32"
                    }
                    environment {
                        TEST_TYPE = "image"
                    }
                    steps {
                        sh "jenkins/run_tests.sh"
                    }
                }
                // Disable RHEL 8.3 image testing for now until we work out the
                // QEMU issues there.
                //
                // stage('RHEL 8.2 image') {
                //     agent {
                //         label "rhel82"
                //     }
                //     environment {
                //         TEST_TYPE = "image"
                //     }
                //     steps {
                //         sh "jenkins/run_tests.sh"
                //     }
                // }
            }
        }
    }
}
