[package]
name = "osbuild-py"
version = "73.0.0"
edition = "2021"

[lib]
name = "osbuild_py"
crate-type = ["cdylib"]

[dependencies]
osbuild = { path = "../osbuild" }
pyo3 = { version = "0.16.5", features = ["extension-module"] }
