name: Coverity
on:
  schedule:
    - cron: '0 5 * * *' # Daily at 05:00 UTC

jobs:
  coverity:
    name: "Test Suite"
    if: github.repository == 'osbuild/osbuild'
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: osbuild
    steps:

      - name: Clone repository
        uses: actions/checkout@v4
        with:
          path: osbuild

      - name: Install Dependencies
        run: |
          sudo apt-get install python3-setuptools

      - name: Download Coverity Tool
        run: |
          make coverity-download
        env:
         COVERITY_TOKEN: ${{ secrets.COVERITY_TOKEN }}

      - name: Coverity check
        run: |
          make coverity-check

      - name: Upload analysis results
        run: |
          make coverity-submit
        env:
         COVERITY_TOKEN: ${{ secrets.COVERITY_TOKEN }}
         COVERITY_EMAIL: ${{ secrets.COVERITY_EMAIL }}
