name: "Differential ShellCheck"
on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    name: "Differential Shell Check"
    runs-on: ubuntu-latest

    steps:
    - name: "Clone Repository"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: "Differential ShellCheck"
      uses: redhat-plumbers-in-action/differential-shellcheck@v3
      with:
        severity: warning
        token: ${{ secrets.GITHUB_TOKEN }}
