name: Mark and close stale issues and PRs

on:
  schedule:
    - cron: '0 4 * * *'

jobs:
  stale:
    runs-on: ubuntu-24.04
    permissions:
      actions: write  # needed to clean up the saved action state
      issues: write
      pull-requests: write
    steps:
      - uses: osbuild/common-stale-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
